spring:
  profiles:
    active: sqlserver
  batch:
    job:
      names:
        ${job.name:NONE}

---
spring:
  config:
    activate:
      on-profile: h2
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb
      username: sa
      password:
      driver-class-name: org.h2.Driver

---
spring:
  config:
    activate:
      on-profile: sqlserver
  datasource:
    hikari:
      jdbc-url: jdbc:sqlserver://localhost:1433;databaseName=master
      username: sa
      password: todak@1234
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
