spring:
  profiles:
    active: local
  batch:
    job:
      names: ${job.name:NONE}
    initialize-schema: never
  jpa:
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace
    org.springframeword.batch: debug

---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    hikari:
      jdbc-url: jdbc:sqlserver://localhost:1433;databaseName=master
      username: sa
      password: todak@1234
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.h2.Driver
  batch:
    job:
      names: ${job.name:NONE}
    initialize-schema: embedded
